- name: add vmware apt key
  apt_key:
    url: https://packages.vmware.com/tools/keys/VMWARE-PACKAGING-GPG-RSA-KEY.pub
  become: true
  when: ansible_facts['distribution_major_version'] == "14"

- name: add vmware apt repository
  apt_repository:
    repo: deb https://packages.vmware.com/packages/ubuntu {{ ansible_facts['distribution_release'] }} main
    filename: vmware-tools
  become: true
  when: ansible_facts['distribution_major_version'] == "14"

- name: install open-vm-tools-deploypkg
  apt:
    name: open-vm-tools-deploypkg
    # The key situation with this repo is kind of a disaster these days
    allow_unauthenticated: true
  become: true
  when: ansible_facts['distribution_major_version'] == "14"
