- name: install rsyslog-gnutls (apt)
  apt:
    name: rsyslog-gnutls
  become: true
  when: ansible_facts['pkg_mgr'] == "apt"

- name: install rsyslog-gnutls (yum)
  yum:
    name: rsyslog-gnutls
  become: true
  when: ansible_facts['pkg_mgr'] == "yum"

- name: install papertrail certificate bundle
  get_url:
    url: https://papertrailapp.com/tools/papertrail-bundle.pem
    dest: /etc/papertrail-bundle.pem
  become: true

- name: configure rsyslog to target papertrail
  template:
    src: etc_rsyslog_d_papertrail.conf.j2
    dest: /etc/rsyslog.d/papertrail.conf
  become: true
